### PR TITLE
Blog App - processing data in models2

### PR DESCRIPTION
**Pull request by HENRYKC24**
## In this pull request, I did these:
- Users
A method that returns the 3 most recent posts for a given user.
- Posts
A method that updates the posts counter for a user.
A method that returns the 5 most recent comments for a given post.
-Comments
A method that updates the comments counter for a post.
- Likes
A method that updates the likes counter for a post.
made current user data available to all controllers.

- Created a method called current_user in my ApplicationController.
- The current_user method returns the first user from a database.

### CODE REVIEW

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
- [ ] Please make sure you have all the changes in the pull request. 

You can also consider:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by HENRYKC24** [comment]
Please, can you give me more tips:pray:
Which changes are missing exactly? Thank you.

**Comment by arslanbisharat** [comment]
> Please, can you give me more tips🙏 Which changes are missing exactly? Thank you.

@HENRYKC24  When you create a pull request make sure there are all the commits present related to the project. I hope this makes sense. currently, you have empty lines added. Please check https://github.com/HENRYKC24/Blog_App/pull/7/files

**Comment by HENRYKC24** [comment]
This project was already approved and because I am repeating the week, I just needed to make some changes in the files to allow you to gain access to the files. Does that make any sense, please?

**Comment by HENRYKC24** [comment]
This is the link to the already approved CRR
https://github.com/HENRYKC24/Blog_App/pull/5

**Comment by arslanbisharat** [comment]
> This project was already approved and because I am repeating the week, I just needed to make some changes in the files to allow you to gain access to the files. Does that make any sense, please?

Sure thank you

**Review by arslanbisharat — APPROVED** [review]
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

To Highlight: 
- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

**Comment by HENRYKC24** [comment]
Thank you so much.

**Pull request merged**
