### PR TITLE
integration specs for views

### PR DESCRIPTION
**Pull request by tufoinnkuo10**
In this milestone, we did the following;
Add test for the app following sections
- Login page:
- User index page:
- user show page:
- User post index page
- Post show page:

### CODE REVIEW

**Review by Emmyn5600 — CHANGES_REQUESTED** [review]
Hi @HENRYKC24  and @tufoinnkuo10  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet, please work on it and ask for another review.


 ## Required Changes ♻️

- KIndly fix this issue to make your tests running
 
image

image

- Some of your tests are running but others don't. Please fix them

image

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by HENRYKC24** [comment]
@Emmyn5600 thank you for your review. Please, we are confused about these failures in your machine. We have all the tests passing at our respective machines (mine and that of my partner's). Watch this :point_down:

rspec

What do you suggest we do in this case?

Thank you.

**Comment by HENRYKC24** [comment]
@Emmyn5600 I think you need to run our tests in the "/spec/views" folder.

**Comment by HENRYKC24** [comment]
@Emmyn5600, we are also confused because you are treating this code review request as a re-review. That was our very first submission. Please, check this as we have less time to complete all our tasks for this week.

Thank you.

**Comment by Emmyn5600** [comment]
To the next code reviewer, the tests are passing once you run the `rspec spec/views` instead of `bundle exec rspec`.

image

**Comment by HENRYKC24** [comment]
Thank you, @Emmyn5600. We greatly appreciate your level of professionalism.

**Review by oloomoses — APPROVED** [review]
Hi @HENRYKC24 and @tufoinnkuo10 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

_Slack: Oloo Moses_
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by HENRYKC24** [comment]
Thank you @oloomoses. We will go ahead to merge the pull request as you directed:running:

**Pull request merged**
